### ISSUE TITLE
Support for heroku-18 stack

### ISSUE THREAD

**Issue by Antoine007** [rails-sqlserver/heroku-buildpack-freetds#4]
Hi,

We upgraded to heroku-18 and now the buildpack breaks on new deploys / our review apps.
Help would be much appreciated 🙏👍😄

**Comment by arnoldmarunda** [comment]
I have added the build pack to a Heroku-18 stack
`heroku config:add BUILDPACK_URL=https://github.com/rails-sqlserver/heroku-buildpack-freetds`

I have pushed
`git push heroku master`

But push is rejected with the following error
`remote: -----> FreeTDS app detected                                                                                                                            
remote:        BIN_DIR=/app/tmp/buildpacks/d88fc40c5dcf1eef3fed7273a650e47a4c4d420cd6cbd8072c75090d3fcdaa6933aa17b8bfc16bcf00ac2ca30a1f99a38bfb51deb95e54626545
d71fef200514/bin, ROOT_DIR=/app/tmp/buildpacks/d88fc40c5dcf1eef3fed7273a650e47a4c4d420cd6cbd8072c75090d3fcdaa6933aa17b8bfc16bcf00ac2ca30a1f99a38bfb51deb95e5462
6545d71fef200514, BUILD_DIR=/tmp/build_ae89e07b2aefa7675f8a78b04f3a3021, CACHE_DIR=/app/tmp/cache, pwd=/app/tmp/buildpacks/d88fc40c5dcf1eef3fed7273a650e47a4c4d
420cd6cbd8072c75090d3fcdaa6933aa17b8bfc16bcf00ac2ca30a1f99a38bfb51deb95e54626545d71fef200514                                                                   
remote: -----> [2019-01-24 20:02:00] FreeTDS 1.00.21 building in /tmp/build_ae89e07b2aefa7675f8a78b04f3a3021                                                   
remote: -----> [2019-01-24 20:02:00] Creating .profile.d entry                                                                                                 
remote:        configured APP env vars:                                                                                                                        
remote:          export PATH="/app/freetds/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin"                                                             
remote:          # tiny_tds extconf.rb uses FREETDS_DIR                                                                                                        
remote:          # https://github.com/rails-sqlserver/tiny_tds/blob/5046755ca91594003f8b3ca541d136f3ed859973/ext/tiny_tds/extconf.rb#L36-L38                   
remote:          export FREETDS_DIR="/app/freetds"                                                                                                             
remote:          export LD_LIBRARY_PATH="/app/freetds/lib:/usr/local/lib"                                                                                      
remote:          export LD_RUN_PATH="/app/freetds/lib:/usr/local/lib"                                                                                          
remote:          export LIBRARY_PATH="/app/freetds/lib:/usr/local/lib"                                                                                         
remote:          export SYBASE="/app/freetds"                                                                                                                  
remote:        Cached files not found - downloading and unpacking...                                                                                           
remote: -----> [2019-01-24 20:02:00] Building FreeTDS against OpenSSL OpenSSL 1.1.0g  2 Nov 2017                                                               
remote: cp: target '/app/freetds/' is not a directory                                                                                                          
remote:        END Running script: compile                                                                                                                     
remote:  !     Push rejected, failed to compile FreeTDS app.                                                                                                   
remote:                                                                                                                                                        
remote:  !     Push failed                                   `

What am I doing wrong? Your assistance is greatly appreciated

**Comment by RaresSalcudean** [comment]
Any updates on this thread? We are trying to use FreeDTS on heroku-18 stack, and getting the error from above.

**Comment by cireficc** [comment]
@RaresSalcudean The config needs to be changed for heroku-18 (because the ENV variable name changed between stacks). You can see [a fork here](https://github.com/x-b-e/heroku-buildpack-freetds/compare/master...cn-platenius:master) that has made that change and will work as a buildpack on Heroku.

**Comment by RaresSalcudean** [comment]
@cireficc I did a fork and made the changes then added the buildpack to Heroku and it still failed. 
Hers are the logs:

**Note:** I deployed with version 1.3.0, is it fine to use v1.3.0? Are there huge differences between the latest version?

Sorry for the long log.

```
-----> FreeTDS app detected
       BIN_DIR=/app/tmp/buildpacks/966614a3ae293808ac8f2c638e777d027696d30556d2ebca7d99f82ec7d94dd0f5733bde7cfd38b4dedd0ed5d56099b8802eda5f4debd1e63f3e8ea5ebddcb70/bin, ROOT_DIR=/app/tmp/buildpacks/966614a3ae293808ac8f2c638e777d027696d30556d2ebca7d99f82ec7d94dd0f5733bde7cfd38b4dedd0ed5d56099b8802eda5f4debd1e63f3e8ea5ebddcb70, BUILD_DIR=/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b, CACHE_DIR=/app/tmp/cache, pwd=/app/tmp/buildpacks/966614a3ae293808ac8f2c638e777d027696d30556d2ebca7d99f82ec7d94dd0f5733bde7cfd38b4dedd0ed5d56099b8802eda5f4debd1e63f3e8ea5ebddcb70
-----> [2019-08-27 06:41:36] FreeTDS 1.00.21 building in /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b
-----> [2019-08-27 06:41:36] Creating .profile.d entry
       configured APP env vars:
         export PATH="/app/freetds/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin"
         # tiny_tds extconf.rb uses FREETDS_DIR
         # https://github.com/rails-sqlserver/tiny_tds/blob/5046755ca91594003f8b3ca541d136f3ed859973/ext/tiny_tds/extconf.rb#L36-L38
         export FREETDS_DIR="/app/freetds"
         export LD_LIBRARY_PATH="/app/freetds/lib:/usr/local/lib"
         export LD_RUN_PATH="/app/freetds/lib:/usr/local/lib"
         export LIBRARY_PATH="/app/freetds/lib:/usr/local/lib"
         export SYBASE="/app/freetds"
       Cached files not found - downloading and unpacking...
-----> [2019-08-27 06:41:37] Building FreeTDS against OpenSSL OpenSSL 1.1.0g  2 Nov 2017
-----> [2019-08-27 06:42:06] Testing build
-----> [2019-08-27 06:42:06] Caching FreeTDS installation
       Unpacking cached files...
       configured BUILDPACK env vars:
       declare -x FREETDS_DIR="/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/freetds"
       declare -x LD_LIBRARY_PATH="/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/freetds/lib:/app/freetds/lib:/usr/local/lib"
       declare -x LIBRARY_PATH="/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/freetds/lib:/app/freetds/lib:/usr/local/lib"
       declare -x PATH="/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/freetds/bin:/app/freetds/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin"
       declare -x SYBASE="/app/freetds"
       Install of FreeTDS 1.00.21 complete
       END Running script: compile
-----> HerokuRuntimeMetrics app detected
-----> Setting up .profile.d to automatically run metrics agent...
-----> ActiveStorage Preview app detected
-----> Installing binary dependencies for ActiveStorage Preview
       Downloading packages..
       Installing packages.............
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.0
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/...........
       Using rake 12.3.3
       Using concurrent-ruby 1.1.5
       Using minitest 5.11.3
       Using thread_safe 0.3.6
       Using builder 3.2.3
       Using erubi 1.8.0
       Using mini_portile2 2.4.0
       Using crass 1.0.4
       Using rack 2.0.7
       Using nio4r 2.4.0
       Using websocket-extensions 0.1.4
       Using mini_mime 1.0.2
       Using method_source 0.9.2
       Using thor 0.20.3
       Using jsonapi-renderer 0.2.2
       Using arel 9.0.0
       Using mimemagic 0.3.3
       Using aws-eventstream 1.0.3
       Using aws-partitions 1.193.0
       Using jmespath 1.4.0
       Using aws-sigv2 1.0.1
       Using multi_json 1.13.1
       Using statsd-ruby 1.4.0
       Using bcrypt 3.1.13
       Using msgpack 1.3.0
       Using bundler 2.0.2
       Using cancancan 3.0.1
       Using chronic 0.10.2
       Using coffee-script-source 1.12.2
       Using execjs 2.7.0
       Using connection_pool 2.2.2
       Using dalli 2.7.10
       Using orm_adapter 0.5.0
       Using jwt 2.2.1
       Using multipart-post 2.1.1
       Using ffi 1.11.1
       Using raabro 1.1.6
       Using temple 0.8.1
       Using tilt 2.0.9
       Using honeybadger 4.5.0
       Using mime-types-data 3.2019.0331
       Using multi_xml 0.6.0
       Using newrelic_rpm 6.5.0.357
       Using pagy 3.4.1
       Using parallel 1.17.0
       Using pg 1.1.4
       Using puma 3.12.1
       Using rack-cors 1.0.3
       Using rb-fsevent 0.10.3
       Using redis 4.1.2
       Fetching tiny_tds 2.1.2
       Using upsert 2.2.1
       Using zip-codes 0.2.1
       Using i18n 1.6.0
       Using tzinfo 1.2.5
       Using nokogiri 1.10.3
       Using dry-core 0.4.8
       Using mail 2.7.1
       Using marcel 0.3.3
       Using aws-sigv4 1.1.0
       Using barnes 0.0.7
       Using bootsnap 1.4.4
       Using websocket-driver 0.7.1
       Using rack-test 1.1.0
       Using warden 1.2.8
       Using request_store 1.4.1
       Using rack-protection 2.0.5
       Using sprockets 3.7.2
       Using coffee-script 2.4.1
       Using uglifier 4.1.20
       Using faraday 0.15.4
       Using haml 5.1.1
       Using mime-types 3.2.2
       Using rb-inotify 0.10.0
       Using et-orbi 1.2.1
       Using activesupport 5.2.3
       Using loofah 2.2.3
       Using aws-sdk-core 3.61.1
       Using dry-configurable 0.8.3
       Using sentry-raven 2.9.0
       Using sidekiq 5.2.7
       Using httparty 0.16.4
       Using rails-html-sanitizer 1.0.4
       Using aws-sdk-acm 1.25.0
       Using aws-sdk-acmpca 1.20.0
       Using aws-sdk-alexaforbusiness 1.29.0
       Using aws-sdk-amplify 1.10.0
       Using aws-sdk-apigateway 1.34.0
       Using aws-sdk-apigatewaymanagementapi 1.9.0
       Using aws-sdk-apigatewayv2 1.13.0
       Using aws-sdk-applicationautoscaling 1.28.0
       Using aws-sdk-applicationdiscoveryservice 1.21.0
       Using aws-sdk-applicationinsights 1.2.0
       Using aws-sdk-appmesh 1.13.0
       Using aws-sdk-appstream 1.34.0
       Using aws-sdk-appsync 1.19.0
       Using aws-sdk-athena 1.18.0
       Using aws-sdk-autoscaling 1.27.0
       Using aws-sdk-autoscalingplans 1.18.0
       Using aws-sdk-backup 1.9.0
       Using aws-sdk-batch 1.23.0
       Using aws-sdk-budgets 1.25.0
       Using aws-sdk-chime 1.13.0
       Using aws-sdk-cloud9 1.17.0
       Using aws-sdk-cloudformation 1.25.0
       Using aws-sdk-clouddirectory 1.20.0
       Using aws-sdk-cloudfront 1.22.0
       Using aws-sdk-cloudhsm 1.18.0
       Using aws-sdk-cloudhsmv2 1.18.0
       Using aws-sdk-cloudsearch 1.15.0
       Using aws-sdk-cloudsearchdomain 1.15.0
       Using aws-sdk-cloudtrail 1.17.0
       Using aws-sdk-cloudwatch 1.27.0
       Using aws-sdk-cloudwatchevents 1.24.0
       Using aws-sdk-cloudwatchlogs 1.24.0
       Using aws-sdk-codebuild 1.39.0
       Using aws-sdk-codecommit 1.26.0
       Using aws-sdk-codedeploy 1.26.0
       Using aws-sdk-codepipeline 1.23.0
       Using aws-sdk-codestar 1.17.0
       Using aws-sdk-cognitoidentity 1.16.0
       Using aws-sdk-cognitoidentityprovider 1.25.0
       Using aws-sdk-cognitosync 1.15.0
       Using aws-sdk-comprehend 1.25.0
       Using aws-sdk-comprehendmedical 1.9.0
       Using aws-sdk-configservice 1.35.0
       Using aws-sdk-connect 1.19.0
       Using aws-sdk-costandusagereportservice 1.16.0
       Using aws-sdk-costexplorer 1.28.0
       Using aws-sdk-databasemigrationservice 1.27.0
       Using aws-sdk-datasync 1.10.0
       Using aws-sdk-dax 1.17.0
       Using aws-sdk-datapipeline 1.15.0
       Installing tiny_tds 2.1.2 with native extensions
       Using aws-sdk-devicefarm 1.27.0
       Using aws-sdk-directconnect 1.24.0
       Using aws-sdk-directoryservice 1.21.0
       Using aws-sdk-dlm 1.18.0
       Using aws-sdk-docdb 1.10.0
       Using aws-sdk-dynamodb 1.34.0
       Using aws-sdk-dynamodbstreams 1.15.0
       Using aws-sdk-ec2 1.101.0
       Using aws-sdk-ec2instanceconnect 1.2.0
       Using aws-sdk-ecr 1.20.0
       Using aws-sdk-ecs 1.45.0
       Using aws-sdk-efs 1.21.0
       Using aws-sdk-eks 1.24.0
       Using aws-sdk-elasticache 1.23.0
       Using aws-sdk-elasticbeanstalk 1.25.0
       Using aws-sdk-elasticloadbalancing 1.18.0
       Using aws-sdk-elasticloadbalancingv2 1.33.0
       Using aws-sdk-elasticsearchservice 1.26.0
       Using aws-sdk-elastictranscoder 1.17.0
       Using aws-sdk-emr 1.20.0
       Using aws-sdk-eventbridge 1.1.0
       Using aws-sdk-firehose 1.20.0
       Using aws-sdk-fms 1.18.0
       Using aws-sdk-fsx 1.11.0
       Using aws-sdk-gamelift 1.23.0
       Using aws-sdk-glacier 1.25.0
       Using aws-sdk-globalaccelerator 1.10.0
       Using aws-sdk-glue 1.40.0
       Using aws-sdk-greengrass 1.23.0
       Using aws-sdk-groundstation 1.3.0
       Using aws-sdk-guardduty 1.22.0
       Using aws-sdk-health 1.19.0
       Using aws-sdk-iam 1.29.0
       Using aws-sdk-importexport 1.15.0
       Using aws-sdk-inspector 1.22.0
       Using aws-sdk-iot 1.35.0
       Using aws-sdk-iot1clickdevicesservice 1.17.0
       Using aws-sdk-iot1clickprojects 1.17.0
       Using aws-sdk-iotanalytics 1.24.0
       Using aws-sdk-iotdataplane 1.15.0
       Using aws-sdk-iotevents 1.4.0
       Using aws-sdk-ioteventsdata 1.4.0
       Using aws-sdk-iotjobsdataplane 1.16.0
       Using aws-sdk-iotthingsgraph 1.3.0
       Using aws-sdk-kafka 1.12.0
       Using aws-sdk-kinesis 1.19.0
       Using aws-sdk-kinesisanalytics 1.19.0
       Using aws-sdk-kinesisanalyticsv2 1.10.0
       Using aws-sdk-kinesisvideo 1.19.0
       Using aws-sdk-kinesisvideoarchivedmedia 1.18.0
       Using aws-sdk-kinesisvideomedia 1.17.0
       Using aws-sdk-kms 1.24.0
       Using aws-sdk-lambda 1.29.0
       Using aws-sdk-lambdapreview 1.15.0
       Using aws-sdk-lex 1.18.0
       Using aws-sdk-lexmodelbuildingservice 1.21.0
       Using aws-sdk-licensemanager 1.9.0
       Using aws-sdk-lightsail 1.24.0
       Using aws-sdk-machinelearning 1.16.0
       Using aws-sdk-macie 1.15.0
       Using aws-sdk-managedblockchain 1.6.0
       Using aws-sdk-marketplacecommerceanalytics 1.15.0
       Using aws-sdk-marketplaceentitlementservice 1.15.0
       Using aws-sdk-marketplacemetering 1.18.0
       Using aws-sdk-mediaconnect 1.12.0
       Using aws-sdk-mediaconvert 1.32.0
       Using aws-sdk-medialive 1.36.0
       Using aws-sdk-mediapackage 1.22.0
       Using aws-sdk-mediapackagevod 1.4.0
       Using aws-sdk-mediastore 1.19.0
       Using aws-sdk-mediastoredata 1.18.0
       Using aws-sdk-mediatailor 1.20.0
       Using aws-sdk-migrationhub 1.17.0
       Using aws-sdk-mobile 1.15.0
       Using aws-sdk-mq 1.20.0
       Using aws-sdk-mturk 1.18.0
       Using aws-sdk-neptune 1.18.0
       Using aws-sdk-opsworks 1.20.0
       Using aws-sdk-opsworkscm 1.23.0
       Using aws-sdk-organizations 1.31.0
       Using aws-sdk-personalize 1.4.0
       Using aws-sdk-personalizeevents 1.3.0
       Using aws-sdk-personalizeruntime 1.3.0
       Using aws-sdk-pi 1.15.0
       Using aws-sdk-pinpoint 1.27.0
       Using aws-sdk-pinpointemail 1.14.0
       Using aws-sdk-pinpointsmsvoice 1.12.0
       Using aws-sdk-polly 1.25.0
       Using aws-sdk-pricing 1.15.0
       Using aws-sdk-quicksight 1.12.0
       Using aws-sdk-ram 1.10.0
       Using aws-sdk-rds 1.63.0
       Using aws-sdk-rdsdataservice 1.11.0
       Using aws-sdk-redshift 1.30.0
       Using aws-sdk-rekognition 1.28.0
       Using aws-sdk-resourcegroups 1.20.0
       Using aws-sdk-resourcegroupstaggingapi 1.17.0
       Using aws-sdk-robomaker 1.13.0
       Using aws-sdk-route53 1.28.0
       Using aws-sdk-route53domains 1.17.0
       Using aws-sdk-route53resolver 1.10.0
       Using aws-sdk-s3control 1.12.0
       Using aws-sdk-sagemaker 1.41.0
       Using aws-sdk-sagemakerruntime 1.16.0
       Using aws-sdk-secretsmanager 1.31.0
       Using aws-sdk-securityhub 1.12.0
       Using aws-sdk-serverlessapplicationrepository 1.21.0
       Using aws-sdk-servicecatalog 1.32.0
       Using aws-sdk-servicediscovery 1.18.0
       Using aws-sdk-servicequotas 1.2.0
       Using aws-sdk-ses 1.25.0
       Using aws-sdk-shield 1.20.0
       Using aws-sdk-signer 1.15.0
       Using aws-sdk-simpledb 1.15.0
       Using aws-sdk-sms 1.16.0
       Using aws-sdk-snowball 1.20.0
       Using aws-sdk-sns 1.19.0
       Using aws-sdk-sqs 1.20.0
       Using aws-sdk-ssm 1.54.0
       Using aws-sdk-states 1.20.0
       Using aws-sdk-storagegateway 1.30.0
       Using aws-sdk-support 1.15.0
       Using aws-sdk-swf 1.16.0
       Using aws-sdk-textract 1.10.0
       Using aws-sdk-transcribeservice 1.26.0
       Using aws-sdk-transcribestreamingservice 1.8.0
       Using aws-sdk-transfer 1.12.0
       Using aws-sdk-translate 1.17.0
       Using aws-sdk-waf 1.24.0
       Using aws-sdk-wafregional 1.25.0
       Using aws-sdk-workdocs 1.18.0
       Using aws-sdk-worklink 1.11.0
       Using aws-sdk-workmail 1.18.0
       Using aws-sdk-workspaces 1.27.0
       Using aws-sdk-xray 1.20.0
       Using dry-container 0.7.2
       Using fugit 1.3.0
       Using sass-listen 4.0.0
       Using rails-dom-testing 2.0.3
       Using globalid 0.4.2
       Using activemodel 5.2.3
       Using case_transform 0.2
       Using carmen 1.1.3
       Using fast_jsonapi 1.5
       Using aws-sdk-s3 1.46.0
       Using actionview 5.2.3
       Using activejob 5.2.3
       Using activerecord 5.2.3
       Using aws-sdk-resources 3.50.0
       Using dry-auto_inject 0.6.1
       Using sass 3.7.4
       Using sidekiq-cron 1.1.0
       Using actionpack 5.2.3
       Using activerecord-import 1.0.2
       Using amoeba 3.1.0
       Using audited 4.9.0
       Using aws-sdk 3.0.1
       Using pg_party 1.0.1 from https://github.com/rkrage/pg_party (at master@8468543)
       Using warden-jwt_auth 0.3.6
       Using actioncable 5.2.3
       Using actionmailer 5.2.3
       Using railties 5.2.3
       Using active_model_serializers 0.10.10
       Using activestorage 5.2.3
       Using gon 6.2.1
       Using sprockets-rails 3.2.1
       Using actionpack-xml_parser 2.0.1
       Using coffee-rails 5.0.0
       Using responders 3.0.0
       Using rails 5.2.3
       Using sass-rails 5.0.7
       Using devise 4.6.2
       Using devise-jwt 0.5.9
       Using simple_token_authentication 1.15.1
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/gems/tiny_tds-2.1.2/ext/tiny_tds
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/bin/ruby -I
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/lib/ruby/2.6.0 -r
       ./siteconf20190827-7696-ppwws2.rb extconf.rb
       checking for sybfront.h... no
       checking for sybdb.h... no
       checking for tdsdbopen() in -lsybdb... no
       checking for dbanydatecrack() in -lsybdb... no
       Failed! Do you have FreeTDS 0.95.80 or higher installed?
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       
       Provided configuration options:
       	--with-opt-dir
       	--without-opt-dir
       	--with-opt-include
       	--without-opt-include=${opt-dir}/include
       	--with-opt-lib
       	--without-opt-lib=${opt-dir}/lib
       	--with-make-prog
       	--without-make-prog
       	--srcdir=.
       	--curdir
       --ruby=/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/bin/$(RUBY_BASE_NAME)
       	--help
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-sybdblib
       	--without-sybdblib
       	--with-sybdblib
       	--without-sybdblib
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/tiny_tds-2.1.2/mkmf.log
       
       extconf failed, exit code 1
       
       Gem files will remain installed in
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/gems/tiny_tds-2.1.2
       for inspection.
       Results logged to
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/tiny_tds-2.1.2/gem_make.out
       
       An error occurred while installing tiny_tds (2.1.2), and Bundler cannot
       continue.
       Make sure that `gem install tiny_tds -v '2.1.2' --source
       'https://rubygems.org/'` succeeds before bundling.
       
       In Gemfile:
         tiny_tds
       Bundler Output: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/...........
       Using rake 12.3.3
       Using concurrent-ruby 1.1.5
       Using minitest 5.11.3
       Using thread_safe 0.3.6
       Using builder 3.2.3
       Using erubi 1.8.0
       Using mini_portile2 2.4.0
       Using crass 1.0.4
       Using rack 2.0.7
       Using nio4r 2.4.0
       Using websocket-extensions 0.1.4
       Using mini_mime 1.0.2
       Using method_source 0.9.2
       Using thor 0.20.3
       Using jsonapi-renderer 0.2.2
       Using arel 9.0.0
       Using mimemagic 0.3.3
       Using aws-eventstream 1.0.3
       Using aws-partitions 1.193.0
       Using jmespath 1.4.0
       Using aws-sigv2 1.0.1
       Using multi_json 1.13.1
       Using statsd-ruby 1.4.0
       Using bcrypt 3.1.13
       Using msgpack 1.3.0
       Using bundler 2.0.2
       Using cancancan 3.0.1
       Using chronic 0.10.2
       Using coffee-script-source 1.12.2
       Using execjs 2.7.0
       Using connection_pool 2.2.2
       Using dalli 2.7.10
       Using orm_adapter 0.5.0
       Using jwt 2.2.1
       Using multipart-post 2.1.1
       Using ffi 1.11.1
       Using raabro 1.1.6
       Using temple 0.8.1
       Using tilt 2.0.9
       Using honeybadger 4.5.0
       Using mime-types-data 3.2019.0331
       Using multi_xml 0.6.0
       Using newrelic_rpm 6.5.0.357
       Using pagy 3.4.1
       Using parallel 1.17.0
       Using pg 1.1.4
       Using puma 3.12.1
       Using rack-cors 1.0.3
       Using rb-fsevent 0.10.3
       Using redis 4.1.2
       Fetching tiny_tds 2.1.2
       Using upsert 2.2.1
       Using zip-codes 0.2.1
       Using i18n 1.6.0
       Using tzinfo 1.2.5
       Using nokogiri 1.10.3
       Using dry-core 0.4.8
       Using mail 2.7.1
       Using marcel 0.3.3
       Using aws-sigv4 1.1.0
       Using barnes 0.0.7
       Using bootsnap 1.4.4
       Using websocket-driver 0.7.1
       Using rack-test 1.1.0
       Using warden 1.2.8
       Using request_store 1.4.1
       Using rack-protection 2.0.5
       Using sprockets 3.7.2
       Using coffee-script 2.4.1
       Using uglifier 4.1.20
       Using faraday 0.15.4
       Using haml 5.1.1
       Using mime-types 3.2.2
       Using rb-inotify 0.10.0
       Using et-orbi 1.2.1
       Using activesupport 5.2.3
       Using loofah 2.2.3
       Using aws-sdk-core 3.61.1
       Using dry-configurable 0.8.3
       Using sentry-raven 2.9.0
       Using sidekiq 5.2.7
       Using httparty 0.16.4
       Using rails-html-sanitizer 1.0.4
       Using aws-sdk-acm 1.25.0
       Using aws-sdk-acmpca 1.20.0
       Using aws-sdk-alexaforbusiness 1.29.0
       Using aws-sdk-amplify 1.10.0
       Using aws-sdk-apigateway 1.34.0
       Using aws-sdk-apigatewaymanagementapi 1.9.0
       Using aws-sdk-apigatewayv2 1.13.0
       Using aws-sdk-applicationautoscaling 1.28.0
       Using aws-sdk-applicationdiscoveryservice 1.21.0
       Using aws-sdk-applicationinsights 1.2.0
       Using aws-sdk-appmesh 1.13.0
       Using aws-sdk-appstream 1.34.0
       Using aws-sdk-appsync 1.19.0
       Using aws-sdk-athena 1.18.0
       Using aws-sdk-autoscaling 1.27.0
       Using aws-sdk-autoscalingplans 1.18.0
       Using aws-sdk-backup 1.9.0
       Using aws-sdk-batch 1.23.0
       Using aws-sdk-budgets 1.25.0
       Using aws-sdk-chime 1.13.0
       Using aws-sdk-cloud9 1.17.0
       Using aws-sdk-cloudformation 1.25.0
       Using aws-sdk-clouddirectory 1.20.0
       Using aws-sdk-cloudfront 1.22.0
       Using aws-sdk-cloudhsm 1.18.0
       Using aws-sdk-cloudhsmv2 1.18.0
       Using aws-sdk-cloudsearch 1.15.0
       Using aws-sdk-cloudsearchdomain 1.15.0
       Using aws-sdk-cloudtrail 1.17.0
       Using aws-sdk-cloudwatch 1.27.0
       Using aws-sdk-cloudwatchevents 1.24.0
       Using aws-sdk-cloudwatchlogs 1.24.0
       Using aws-sdk-codebuild 1.39.0
       Using aws-sdk-codecommit 1.26.0
       Using aws-sdk-codedeploy 1.26.0
       Using aws-sdk-codepipeline 1.23.0
       Using aws-sdk-codestar 1.17.0
       Using aws-sdk-cognitoidentity 1.16.0
       Using aws-sdk-cognitoidentityprovider 1.25.0
       Using aws-sdk-cognitosync 1.15.0
       Using aws-sdk-comprehend 1.25.0
       Using aws-sdk-comprehendmedical 1.9.0
       Using aws-sdk-configservice 1.35.0
       Using aws-sdk-connect 1.19.0
       Using aws-sdk-costandusagereportservice 1.16.0
       Using aws-sdk-costexplorer 1.28.0
       Using aws-sdk-databasemigrationservice 1.27.0
       Using aws-sdk-datasync 1.10.0
       Using aws-sdk-dax 1.17.0
       Using aws-sdk-datapipeline 1.15.0
       Installing tiny_tds 2.1.2 with native extensions
       Using aws-sdk-devicefarm 1.27.0
       Using aws-sdk-directconnect 1.24.0
       Using aws-sdk-directoryservice 1.21.0
       Using aws-sdk-dlm 1.18.0
       Using aws-sdk-docdb 1.10.0
       Using aws-sdk-dynamodb 1.34.0
       Using aws-sdk-dynamodbstreams 1.15.0
       Using aws-sdk-ec2 1.101.0
       Using aws-sdk-ec2instanceconnect 1.2.0
       Using aws-sdk-ecr 1.20.0
       Using aws-sdk-ecs 1.45.0
       Using aws-sdk-efs 1.21.0
       Using aws-sdk-eks 1.24.0
       Using aws-sdk-elasticache 1.23.0
       Using aws-sdk-elasticbeanstalk 1.25.0
       Using aws-sdk-elasticloadbalancing 1.18.0
       Using aws-sdk-elasticloadbalancingv2 1.33.0
       Using aws-sdk-elasticsearchservice 1.26.0
       Using aws-sdk-elastictranscoder 1.17.0
       Using aws-sdk-emr 1.20.0
       Using aws-sdk-eventbridge 1.1.0
       Using aws-sdk-firehose 1.20.0
       Using aws-sdk-fms 1.18.0
       Using aws-sdk-fsx 1.11.0
       Using aws-sdk-gamelift 1.23.0
       Using aws-sdk-glacier 1.25.0
       Using aws-sdk-globalaccelerator 1.10.0
       Using aws-sdk-glue 1.40.0
       Using aws-sdk-greengrass 1.23.0
       Using aws-sdk-groundstation 1.3.0
       Using aws-sdk-guardduty 1.22.0
       Using aws-sdk-health 1.19.0
       Using aws-sdk-iam 1.29.0
       Using aws-sdk-importexport 1.15.0
       Using aws-sdk-inspector 1.22.0
       Using aws-sdk-iot 1.35.0
       Using aws-sdk-iot1clickdevicesservice 1.17.0
       Using aws-sdk-iot1clickprojects 1.17.0
       Using aws-sdk-iotanalytics 1.24.0
       Using aws-sdk-iotdataplane 1.15.0
       Using aws-sdk-iotevents 1.4.0
       Using aws-sdk-ioteventsdata 1.4.0
       Using aws-sdk-iotjobsdataplane 1.16.0
       Using aws-sdk-iotthingsgraph 1.3.0
       Using aws-sdk-kafka 1.12.0
       Using aws-sdk-kinesis 1.19.0
       Using aws-sdk-kinesisanalytics 1.19.0
       Using aws-sdk-kinesisanalyticsv2 1.10.0
       Using aws-sdk-kinesisvideo 1.19.0
       Using aws-sdk-kinesisvideoarchivedmedia 1.18.0
       Using aws-sdk-kinesisvideomedia 1.17.0
       Using aws-sdk-kms 1.24.0
       Using aws-sdk-lambda 1.29.0
       Using aws-sdk-lambdapreview 1.15.0
       Using aws-sdk-lex 1.18.0
       Using aws-sdk-lexmodelbuildingservice 1.21.0
       Using aws-sdk-licensemanager 1.9.0
       Using aws-sdk-lightsail 1.24.0
       Using aws-sdk-machinelearning 1.16.0
       Using aws-sdk-macie 1.15.0
       Using aws-sdk-managedblockchain 1.6.0
       Using aws-sdk-marketplacecommerceanalytics 1.15.0
       Using aws-sdk-marketplaceentitlementservice 1.15.0
       Using aws-sdk-marketplacemetering 1.18.0
       Using aws-sdk-mediaconnect 1.12.0
       Using aws-sdk-mediaconvert 1.32.0
       Using aws-sdk-medialive 1.36.0
       Using aws-sdk-mediapackage 1.22.0
       Using aws-sdk-mediapackagevod 1.4.0
       Using aws-sdk-mediastore 1.19.0
       Using aws-sdk-mediastoredata 1.18.0
       Using aws-sdk-mediatailor 1.20.0
       Using aws-sdk-migrationhub 1.17.0
       Using aws-sdk-mobile 1.15.0
       Using aws-sdk-mq 1.20.0
       Using aws-sdk-mturk 1.18.0
       Using aws-sdk-neptune 1.18.0
       Using aws-sdk-opsworks 1.20.0
       Using aws-sdk-opsworkscm 1.23.0
       Using aws-sdk-organizations 1.31.0
       Using aws-sdk-personalize 1.4.0
       Using aws-sdk-personalizeevents 1.3.0
       Using aws-sdk-personalizeruntime 1.3.0
       Using aws-sdk-pi 1.15.0
       Using aws-sdk-pinpoint 1.27.0
       Using aws-sdk-pinpointemail 1.14.0
       Using aws-sdk-pinpointsmsvoice 1.12.0
       Using aws-sdk-polly 1.25.0
       Using aws-sdk-pricing 1.15.0
       Using aws-sdk-quicksight 1.12.0
       Using aws-sdk-ram 1.10.0
       Using aws-sdk-rds 1.63.0
       Using aws-sdk-rdsdataservice 1.11.0
       Using aws-sdk-redshift 1.30.0
       Using aws-sdk-rekognition 1.28.0
       Using aws-sdk-resourcegroups 1.20.0
       Using aws-sdk-resourcegroupstaggingapi 1.17.0
       Using aws-sdk-robomaker 1.13.0
       Using aws-sdk-route53 1.28.0
       Using aws-sdk-route53domains 1.17.0
       Using aws-sdk-route53resolver 1.10.0
       Using aws-sdk-s3control 1.12.0
       Using aws-sdk-sagemaker 1.41.0
       Using aws-sdk-sagemakerruntime 1.16.0
       Using aws-sdk-secretsmanager 1.31.0
       Using aws-sdk-securityhub 1.12.0
       Using aws-sdk-serverlessapplicationrepository 1.21.0
       Using aws-sdk-servicecatalog 1.32.0
       Using aws-sdk-servicediscovery 1.18.0
       Using aws-sdk-servicequotas 1.2.0
       Using aws-sdk-ses 1.25.0
       Using aws-sdk-shield 1.20.0
       Using aws-sdk-signer 1.15.0
       Using aws-sdk-simpledb 1.15.0
       Using aws-sdk-sms 1.16.0
       Using aws-sdk-snowball 1.20.0
       Using aws-sdk-sns 1.19.0
       Using aws-sdk-sqs 1.20.0
       Using aws-sdk-ssm 1.54.0
       Using aws-sdk-states 1.20.0
       Using aws-sdk-storagegateway 1.30.0
       Using aws-sdk-support 1.15.0
       Using aws-sdk-swf 1.16.0
       Using aws-sdk-textract 1.10.0
       Using aws-sdk-transcribeservice 1.26.0
       Using aws-sdk-transcribestreamingservice 1.8.0
       Using aws-sdk-transfer 1.12.0
       Using aws-sdk-translate 1.17.0
       Using aws-sdk-waf 1.24.0
       Using aws-sdk-wafregional 1.25.0
       Using aws-sdk-workdocs 1.18.0
       Using aws-sdk-worklink 1.11.0
       Using aws-sdk-workmail 1.18.0
       Using aws-sdk-workspaces 1.27.0
       Using aws-sdk-xray 1.20.0
       Using dry-container 0.7.2
       Using fugit 1.3.0
       Using sass-listen 4.0.0
       Using rails-dom-testing 2.0.3
       Using globalid 0.4.2
       Using activemodel 5.2.3
       Using case_transform 0.2
       Using carmen 1.1.3
       Using fast_jsonapi 1.5
       Using aws-sdk-s3 1.46.0
       Using actionview 5.2.3
       Using activejob 5.2.3
       Using activerecord 5.2.3
       Using aws-sdk-resources 3.50.0
       Using dry-auto_inject 0.6.1
       Using sass 3.7.4
       Using sidekiq-cron 1.1.0
       Using actionpack 5.2.3
       Using activerecord-import 1.0.2
       Using amoeba 3.1.0
       Using audited 4.9.0
       Using aws-sdk 3.0.1
       Using pg_party 1.0.1 from https://github.com/rkrage/pg_party (at master@8468543)
       Using warden-jwt_auth 0.3.6
       Using actioncable 5.2.3
       Using actionmailer 5.2.3
       Using railties 5.2.3
       Using active_model_serializers 0.10.10
       Using activestorage 5.2.3
       Using gon 6.2.1
       Using sprockets-rails 3.2.1
       Using actionpack-xml_parser 2.0.1
       Using coffee-rails 5.0.0
       Using responders 3.0.0
       Using rails 5.2.3
       Using sass-rails 5.0.7
       Using devise 4.6.2
       Using devise-jwt 0.5.9
       Using simple_token_authentication 1.15.1
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/gems/tiny_tds-2.1.2/ext/tiny_tds
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/bin/ruby -I
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/lib/ruby/2.6.0 -r
       ./siteconf20190827-7696-ppwws2.rb extconf.rb
       checking for sybfront.h... no
       checking for sybdb.h... no
       checking for tdsdbopen() in -lsybdb... no
       checking for dbanydatecrack() in -lsybdb... no
       Failed! Do you have FreeTDS 0.95.80 or higher installed?
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       
       Provided configuration options:
       	--with-opt-dir
       	--without-opt-dir
       	--with-opt-include
       	--without-opt-include=${opt-dir}/include
       	--with-opt-lib
       	--without-opt-lib=${opt-dir}/lib
       	--with-make-prog
       	--without-make-prog
       	--srcdir=.
       	--curdir
       --ruby=/tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/ruby-2.6.0/bin/$(RUBY_BASE_NAME)
       	--help
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-freetds-dir
       	--without-freetds-dir
       	--with-freetds-include
       	--without-freetds-include=${freetds-dir}/include
       	--with-freetds-lib
       	--without-freetds-lib=${freetds-dir}/lib
       	--with-sybdblib
       	--without-sybdblib
       	--with-sybdblib
       	--without-sybdblib
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/tiny_tds-2.1.2/mkmf.log
       
       extconf failed, exit code 1
       
       Gem files will remain installed in
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/gems/tiny_tds-2.1.2
       for inspection.
       Results logged to
       /tmp/build_c7c2ce5b7e8477bd8b6d81d451dd338b/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/tiny_tds-2.1.2/gem_make.out
       
       An error occurred while installing tiny_tds (2.1.2), and Bundler cannot
       continue.
       Make sure that `gem install tiny_tds -v '2.1.2' --source
       'https://rubygems.org/'` succeeds before bundling.
       
       In Gemfile:
         tiny_tds
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by cireficc** [comment]
@RaresSalcudean I ended up using a [different buildpack](https://elements.heroku.com/buildpacks/clickmechanic/heroku-buildpack-freetds) because this one doesn't build TinyTDS properly on Heroku cedar-18. This one can be added via Heroku Elements or manually by using the Github URL. Sadly this buildpack doesn't cache the TinyTDS build so every time you deploy it has to rebuild it from source. In my experience it takes around 1-2 minutes to build TinyTDS then the deploy runs smoothly.

Hopefully rails-sqlserver will update this buildpack to work with cedar-18... but until then this is what I'm using and it works. If you have any idea how to cache library builds in Heroku so that TinyTDS doesn't have to be rebuilt every time, let me know!

**Comment by cireficc** [comment]
@bf4 Thank you for getting this resolved! My deploys are now back down to 30s instead of 3 minutes :)

**Comment by RickEaton** [comment]
The [https://elements.heroku.com/buildpacks/clickmechanic/heroku-buildpack-freetds](url) buildpack no longer seems to be working. Is there an update on getting this pack updated for the heroku-18 stack?

It would be really wonderful to get this fixed - thank you!

**Comment by bf4** [comment]
@RickEaton you may notice that this is a different buildpack than what you referenced?

**Comment by RickEaton** [comment]
Yes, my reference is to the previous commenter, who found the clickmechanic buildpack to be a workaround to heroku-buildpack-freetds not working on Heroku-18. I am unable to get either buildpack to work for me. Are you able to use one of them? I have tried them both as the first buildpack in the build order, followed by the standard Heroku ruby pack. Any help you can provide would be appreciated.

**Comment by bf4** [comment]
Please open a new issue and include any error information useful for
understanding your problem.   A minimal reproduction would be most helpful

**Comment by RickEaton** [comment]
Dear Benjamin,

Thank you for responding to this. I’ve just opened a new issue. Please let me know what additional information you need; let me apologize in advance if the information I’ve provided isn’t sufficient. I am definitely not a systems programmer and appreciate any help you can provide.

Sincerely,

Rick

Rick Eaton
Eaton Nonprofit Solutions
916-718-5063
http://www.eatonnpsolutions.com<http://www.eatonnpsolutions.com/>
